#Even Fibonacci numbers
#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
x, y, z, n, solution = 1, 2, 0, 0, 0
fibonacci_array = [1,2]

while z <= 4000000 do
	z = x + y
	fibonacci_array.push(z)
	x = y
	y = z
end

x, solution = 0, 0


while n < fibonacci_array.length do
	if fibonacci_array[n] % 2 == 0
		solution += fibonacci_array[n]
		n += 1
	else n += 1
	end
end

puts "The solution is #{solution}"


	
